# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0c55eedb2c2181c2a9d1481285b2be2f76e471ef26090f71208ed7af6c168defb76844447357c89462f1a2a314d95b5d67731a23927dc7514fac85529a7a971

test:
  secret_key_base: 78ff223205524955531e7c7ee829f9ddee6b05fa086c5828b1250227e4648df030f211e5adeab642dc419c328b7adf29d9d335ec5fb5de4667b66fa87a66474b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
